version: '3'
services:
    discovery-service:
        image: discovery-service:latest
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        ports:
            - "8761:8761"
 